# NixOS configuration for test-vm.
#
# Generated by `nix run .#install` on 2026-09-25.
# Edit freely: nothing regenerates this, and the installer only ever
# writes it while installing this machine.
{ ... }:

{
  system.stateVersion = "26.11";

  # Core
  bedtimeLockout.enable = false;
  dataDrive.client.enable = true;
  git.enable = true;
  grub.enable = true;
  nvim.enable = true;
  repo.networkmanager.enable = true;
  tailscale.enable = true;
  vial.enable = false;

  # Desktop
  hyprland.enable = true;

  # Development
  virtual-machines.enable = false;

  # Remote access
  officeNetworkDrives.enable = true;

  # Hosted services
  fleetMonitor.enable = true;
  fleetMonitor.server.enable = false;
  ollama.enable = false;
}
