# Disk layout for test-vm.
#
# Generated by `nix run .#install` on 2026-09-25.
# Edit freely: nothing regenerates this, and the installer only ever
# writes it while installing this machine.
#
# Disko owns this machine's partitioning, so this file describes the
# layout that exists rather than transcribing one that already did.
{ lib, ... }:

(import ../../install/lib/layouts.nix { inherit lib; }).build {
  layout = "plain";
  device = "/dev/vda";
}
