# Roster entry for test-vm.
#
# Generated by `nix run .#install` on 2026-09-25.
# Edit freely: nothing regenerates this, and the installer only ever
# writes it while installing this machine.
{
  system = "x86_64-linux";
  description = "Trying out the new installation process";
  services = [ ];
}
