"""Generating the Nix files a new machine is made of.

These files are committed and read by people afterwards, so they are written to
look like the ones already in the repository rather than like machine output:
`nixfmt` formatting, a comment saying where they came from, and roles grouped
by the categories they were chosen under.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import date

from .model import Catalog, Role


def nix_string(value: str) -> str:
    """Quote a string for Nix, escaping what Nix treats specially."""

    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("${", "\\${")
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def nix_bool(value: bool) -> str:
    return "true" if value else "false"


def _banner(host: str, what: str) -> str:
    return (
        f"# {what} for {host}.\n"
        f"#\n"
        f"# Generated by `nix run .#install` on {date.today().isoformat()}.\n"
        f"# Edit freely: nothing regenerates this, and the installer only ever\n"
        f"# writes it while installing this machine.\n"
    )


def render_meta(host: str, system: str, description: str) -> str:
    """`system/hosts/<host>/meta.nix`, the machine's roster entry."""

    return (
        _banner(host, "Roster entry")
        + "{\n"
        + f"  system = {nix_string(system)};\n"
        + f"  description = {nix_string(description or 'Installed by the installer.')};\n"
        + "  services = [ ];\n"
        + "}\n"
    )


def render_disk(host: str, device: str, layout: str) -> str:
    """`system/hosts/<host>/disk.nix`.

    Unlike the machines that predate the installer, this one is authoritative:
    Disko owns the partitioning and supplies `fileSystems`, so there is no
    generated hardware-configuration.nix beside it.
    """

    return (
        _banner(host, "Disk layout")
        + "#\n"
        + "# Disko owns this machine's partitioning, so this file describes the\n"
        + "# layout that exists rather than transcribing one that already did.\n"
        + "{ lib, ... }:\n"
        + "\n"
        + "(import ../../install/lib/layouts.nix { inherit lib; }).build {\n"
        + f"  layout = {nix_string(layout)};\n"
        + f"  device = {nix_string(device)};\n"
        + "}\n"
    )


def _role_lines(roles: Sequence[Role], selections: Mapping[str, bool]) -> list[str]:
    return [
        f"  {role.name} = {nix_bool(selections[role.id])};"
        for role in roles
        if role.id in selections
    ]


def _grouped_role_block(
    catalog: Catalog, selections: Mapping[str, bool], scope: str
) -> str:
    blocks: list[str] = []
    for category, roles in catalog.grouped():
        in_scope = [role for role in roles if role.scope == scope]
        if not in_scope:
            continue
        lines = _role_lines(sorted(in_scope, key=lambda role: role.name), selections)
        if not lines:
            continue
        blocks.append(f"  # {category.label}\n" + "\n".join(lines))
    return "\n\n".join(blocks)


def render_system_configuration(
    host: str,
    catalog: Catalog,
    selections: Mapping[str, bool],
    state_version: str,
) -> str:
    """`system/hosts/<host>/configuration.nix`.

    Hardware-derived roles are deliberately absent. The committed Facter report
    decides those, and writing them here would let a stale answer outlive the
    hardware that justified it.
    """

    body = _grouped_role_block(catalog, selections, "system")
    return (
        _banner(host, "NixOS configuration")
        + "{ ... }:\n"
        + "\n"
        + "{\n"
        + f"  system.stateVersion = {nix_string(state_version)};\n"
        + ("\n" + body + "\n" if body else "")
        + "}\n"
    )


def render_home_configuration(
    host: str,
    catalog: Catalog,
    selections: Mapping[str, bool],
) -> str:
    """`home/hosts/<host>/default.nix`.

    `laptop.enable` is missing on purpose: home/policy/hardware.nix derives it
    from the same Facter report the NixOS side reads, so it is detected rather
    than answered.
    """

    body = _grouped_role_block(catalog, selections, "home")
    return (
        _banner(host, "Home Manager configuration")
        + "{\n"
        + (body + "\n" if body else "")
        + "}\n"
    )
