# Home Manager configuration for test-vm.
#
# Generated by `nix run .#install` on 2026-09-25.
# Edit freely: nothing regenerates this, and the installer only ever
# writes it while installing this machine.
{
  # Desktop
  desktopEnv.enable = true;

  # Development
  dev.enable = true;
  gameDev.enable = false;

  # Gaming
  gaming.enable = false;

  # 3D printing
  bambu.enable = false;

  # Remote access
  windowsVm.enable = true;
  windowsVm.og.enable = true;
}
