# Home Manager configuration for test-vm.
#
# Generated by `nix run .#install` on 2026-09-28.
# Edit freely: nothing regenerates this, and the installer only ever
# writes it while installing this machine.
{ pkgs, lib, ... }:

let
  wallpaperSource = ../../features/desktop/wallpaper;
  wallpaperctl = pkgs.rustPlatform.buildRustPackage {
    pname = "wallpaperctl";
    version = "0.1.0";
    src = lib.fileset.toSource {
      root = wallpaperSource;
      fileset = lib.fileset.unions [
        (wallpaperSource + "/Cargo.toml")
        (wallpaperSource + "/Cargo.lock")
        (wallpaperSource + "/src")
      ];
    };
    cargoLock.lockFile = wallpaperSource + "/Cargo.lock";
    patches = [ ./wallpaperctl-awww.patch ];
    nativeBuildInputs = [ pkgs.makeWrapper ];
    postFixup = ''
      wrapProgram $out/bin/wallpaperctl \
        --prefix PATH : ${lib.makeBinPath [ pkgs.awww pkgs.imagemagick ]}
    '';
  };
  # Shared autostart.lua launches hyprpaper by name. Replace only that command
  # on this host; wallpaperctl below talks directly to awww (swww's successor).
  wallpaperStartup = pkgs.writeShellScriptBin "hyprpaper" ''
    exec ${lib.getExe' pkgs.awww "awww-daemon"}
  '';
in
{
  # Desktop
  desktopEnv.enable = true;
  home.packages = [
    pkgs.awww
    (lib.hiPrio wallpaperctl)
    (lib.hiPrio wallpaperStartup)
  ];

  # Development
  dev.enable = true;

  # Gaming
  gaming.enable = false;

  # 3D printing
  bambu.enable = false;

  # Remote access
  windowsVm.enable = true;
  windowsVm.og.enable = true;

  # Other
  mediaEditing.enable = false;
}
