font_family Commit Mono
font_size 10.0

enable_audio_bell no
background_opacity 1.0
scrollback_lines 10000
cursor_shape block
hide_window_decorations yes
placement_strategy center
clipboard_control write-clipboard write-primary read-clipboard read-primary

include ~/.config/kitty/github_dark.conf
