class_alias = "chromium-browser", "chromium"
class_alias = "Chromium-browser", "chromium"
class_alias = "plasticx", "plastic"
class_alias = "gcr-prompter", "keyring" 
class_alias = ".blueman-manager-wrapped", "blueman"
class_alias = "com.github.wwmm.easyeffects", "easyeffects"
class_alias = "org.gnome.Nautilus", "nautilus"
class_alias = "org.pwmt.zathura", "zathura"
class_alias = "com.network.manager", "nmgui"
class_alias = ".virt-manager-wrapped", "Virtual Machine Manager"
class_alias = "com.obsproject.Studio", "obs"
class_alias = "org.pulseaudio.pavucontrol", "Volume Control"

# chromium webapps (--app argument)
class_alias = "chrome-chat.openai.com__-Default", "ChatGPT"
class_alias = "chrome-outlook.live.com__mail_0_-Default", "outlook"
class_alias = "chrome-discord.com__channels_@me-Default", "discord"
class_alias = "chrome-calendar.google.com__-Default", "calendar"
class_alias = "chrome-web.whatsapp.com__-Default", "whatsapp"
class_alias = "chrome-play.qobuz.com__user_library_favorites_tracks-Default", "qobuz"
class_alias = "chrome-app.slack.com__client-Default", "slack"
class_alias = "chrome-app.todoist.com__app_upcoming-Default", "todoist"
class_alias = "chrome-excel.cloud.microsoft__open_onedrive_-Default", "excel"
class_alias = "chrome-onedrive.live.com__-Default", "onedrive"
class_alias = "chrome-t470__8123_-Default", "home assistant"
