# GTK/Qt theming.
#
# Deliberately NOT gated on desktopEnv.enable, unlike every other feature under
# desktop/. The headless machines still run GUI programs such as Thunar, which
# are displayed on another machine over Waypipe, and those programs need the
# icon theme and the GTK/Qt environment hints to render correctly. Gating this
# would leave remote windows unthemed.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  gtkThemeName = "Adwaita-dark";
  iconThemeName = "Papirus-Dark";
  kvantumTheme = "KvAdaptaDark";
in
{
  home.packages = [ pkgs.papirus-icon-theme ];

  ###### Environment hints (kept minimal but practical)
  home.sessionVariables = {
    # GTK's built-in dark variant advertises darkness to Electron. The theme
    # name "Adwaita-dark" looks dark in GTK but Electron reports light for it.
    GTK_THEME = "Adwaita:dark";

    # Qt
    QT_STYLE_OVERRIDE = "kvantum";
    QT_QPA_PLATFORMTHEME = "qt6ct"; # if you only have qt5ct, change to "qt5ct"

    # Helps some Electron/Chromium builds pick the right defaults
    XDG_CURRENT_DESKTOP = "Hyprland";
    XDG_SESSION_TYPE = "wayland";
  };

  ###### GTK theming + prefer-dark
  gtk = {
    enable = true;

    theme = {
      name = gtkThemeName;
      package = pkgs.gnome-themes-extra;
    };

    iconTheme = {
      name = iconThemeName;
      package = pkgs.papirus-icon-theme;
    };

    gtk3.extraConfig = {
      "gtk-application-prefer-dark-theme" = 1;
      # Empty left and right groups remove CSD window controls. Window actions
      # remain available through compositor keybinds.
      "gtk-decoration-layout" = ":";
    };

    gtk4.extraConfig = {
      "gtk-application-prefer-dark-theme" = 1;
      "gtk-theme-name" = gtkThemeName;
      "gtk-decoration-layout" = ":";
    };

    gtk4.theme = config.gtk.theme;
  };

  ###### dconf keys that portals + apps actually query
  # Remove only the generated palette files from the previous global theme.
  # Leave any unrelated user CSS untouched; Home Manager will restore its
  # original GTK4 theme stylesheet at activation.
  home.activation.removeGlobalGtkPalette = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    for css in "${config.xdg.configHome}/gtk-3.0/gtk.css" "${config.xdg.configHome}/gtk-4.0/gtk.css"; do
      if [[ -f "$css" ]] && ${pkgs.gnugrep}/bin/grep -q 'Generated by gtk-theme-mode' "$css"; then
        run rm "$css"
      fi
    done
    originalCss="${config.xdg.configHome}/gtk-3.0/gtk.css.pre-gtk-theme-mode.bak"
    if [[ -f "$originalCss" && ! -e "${config.xdg.configHome}/gtk-3.0/gtk.css" ]]; then
      run ${pkgs.coreutils}/bin/cp "$originalCss" "${config.xdg.configHome}/gtk-3.0/gtk.css"
    fi
  '';

  dconf = {
    enable = true;
    settings = {
      "org/gnome/desktop/interface" = {
        color-scheme = "prefer-dark";
        gtk-theme = gtkThemeName;
        icon-theme = iconThemeName;
      };

      # Optional: if you want dark-ish file chooser / dialogs in some GNOME-ish apps
      "org/gnome/desktop/wm/preferences" = {
        theme = gtkThemeName;
        button-layout = ":";
      };
    };
  };

  ###### Kvantum config (Qt dark)
  xdg.configFile."Kvantum/kvantum.kvconfig".text = ''
    [General]
    theme=${kvantumTheme}
  '';

  # Optional: some Qt apps read these
  xdg.configFile."qt5ct/qt5ct.conf".text = ''
    [Appearance]
    style=kvantum
  '';

  xdg.configFile."qt6ct/qt6ct.conf".text = ''
    [Appearance]
    style=kvantum
  '';
}
